### ISSUE TITLE
Issue with server/headless environments

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/CAMIProfilingVisualization#12]
Running the code locally on a system with a GUI is no problem. But when trying to run on a server (running the same version of Ubuntu, but with no GUI), the following error is encountered:
```bash
$ python src/profile_to_plot.py -i data/prediction_multi.profile -g data/ground_truth_multi.profile -b test -s sample_0 genus
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
```

Much googling lead nowhere.

**Comment by luizirber** [comment]
This sounds like an issue with matplotlib defaulting to `qt`, you can try to add a `matplotlibrc` file like we do in sourmash: https://github.com/dib-lab/sourmash/blob/master/matplotlibrc

For `conda` it also helps to use `matplotlib-base` instead of `matplotlib`, I think it avoids bringing `qt` and all the Xorg libs (which also makes environments way smaller)

**Comment by dkoslicki** [comment]
Thanks for the suggestion @luizirber! I’ll give that a try (though I think `ete3` brings in `qt` as well, so might be two issues to address).

**Comment by dkoslicki** [comment]
Turns out just adding `os.environ['QT_QPA_PLATFORM']='offscreen'` before importing matplotlib, seaborn, or ete3 did the trick. So no need to switch to matplotlib-base (though it may indeed make the env smaller, so may be worth doing)
